// Browser acceptance checks use fresh, isolated data and never contact Firebase.
const fs=require('fs'),path=require('path'),http=require('http'),assert=require('node:assert/strict'),{chromium}=require('playwright');
const root=path.resolve(__dirname,'..'),raw=fs.readFileSync(path.join(root,'index.html'),'utf8');
const html=raw.replace('Sync.init();',"Sync.state.status='ready';renderChip();").replace(/\}\)\(\);\s*<\/script>/,'window.__test=expression=>eval(expression);})();\n</script>');
const server=http.createServer((req,res)=>{const name=new URL(req.url,'http://localhost').pathname;if(name==='/'||name==='/index.html'){res.setHeader('Content-Type','text/html');res.end(html);return;}const target=path.resolve(root,'.'+name);if(!target.startsWith(root+path.sep)||name==='/sw.js'||!fs.existsSync(target)){res.writeHead(404);res.end();return;}res.setHeader('Content-Type',name.endsWith('.js')?'text/javascript':name.endsWith('.png')?'image/png':name.endsWith('.webp')?'image/webp':name.endsWith('.svg')?'image/svg+xml':'application/json');res.end(fs.readFileSync(target));});
(async()=>{await new Promise(r=>server.listen(0,'127.0.0.1',r));const browser=await chromium.launch({executablePath:'C:/Program Files (x86)/Microsoft/Edge/Application/msedge.exe',headless:true});fs.mkdirSync(path.join(root,'artifacts'),{recursive:true});
try{for(const width of [360,412,1280]){const context=await browser.newContext({viewport:{width,height:width===1280?1050:915},deviceScaleFactor:2,serviceWorkers:'block'}),page=await context.newPage(),errors=[];page.on('pageerror',e=>errors.push(e.message));await page.goto('http://127.0.0.1:'+server.address().port);await page.locator('.plan-btn-new').click();await page.getByRole('button',{name:'Vorlage wählen'}).click();await page.locator('.studio-template-toggle').first().click();
 const check=async()=>{const m=await page.evaluate(()=>{const dlg=document.querySelector('#studio-dialog'),r=dlg.getBoundingClientRect();return {dialogOverflow:dlg.scrollWidth>dlg.clientWidth+1,pageOverflow:document.documentElement.scrollWidth>innerWidth+1,inside:r.left>=-1&&r.right<=innerWidth+1,small:[...dlg.querySelectorAll('button,input:not([type=range]),select,a.studio-secondary')].filter(e=>{const r=e.getBoundingClientRect();return r.width&&r.height&&(r.width<43.9||r.height<43.9);}).map(e=>e.className)};});assert.equal(m.dialogOverflow,false,JSON.stringify(m));assert.equal(m.pageOverflow,false,JSON.stringify(m));assert.equal(m.inside,true);assert.deepEqual(m.small,[]);};await check();await page.screenshot({path:path.join(root,'artifacts','studio-templates-'+width+'.png'),animations:'disabled'});assert.equal(await page.locator('.studio-template.is-open .studio-template-toggle strong').textContent(),'Ganzkörper');
 await page.getByRole('button',{name:'Vorlage bearbeiten',exact:true}).click();await page.getByRole('button',{name:'Selbst füllen'}).click();await page.getByRole('button',{name:'Übung wählen',exact:true}).first().click();await page.getByLabel('Übung suchen',{exact:true}).fill('brustpresse');await check();await page.screenshot({path:path.join(root,'artifacts','studio-library-'+width+'.png'),animations:'disabled'});await page.getByRole('button',{name:'Information zu Brustpresse',exact:true}).click();await check();await page.screenshot({path:path.join(root,'artifacts','studio-info-'+width+'.png'),animations:'disabled'});await page.getByRole('button',{name:'Zurück',exact:true}).last().click();await page.getByRole('button',{name:'Brustpresse auswählen',exact:true}).click();await check();await page.screenshot({path:path.join(root,'artifacts','studio-editor-'+width+'.png'),animations:'disabled'});
 await page.getByRole('button',{name:'Plan speichern',exact:true}).click();assert.equal(await page.evaluate(()=>window.__test('userPlans.length')),1);assert.equal(await page.evaluate(()=>window.__test('sessions.length')),0);await page.locator('.plan-btn-new').click();await page.getByRole('button',{name:'Plan empfehlen'}).click();await page.getByRole('button',{name:'Weiter',exact:true}).click();await check();await page.screenshot({path:path.join(root,'artifacts','studio-interview-'+width+'.png'),animations:'disabled'});await page.getByRole('button',{name:'Ich starte gerade',exact:true}).click();assert.equal(await page.evaluate(()=>window.__test('StudioUI.state.input.years')),0);assert.deepEqual(errors,[]);console.log('PASS: Studio '+width+'px, accordion, equipment/library, editor, interview, 44px actions and isolated commit');await context.close();}
}finally{await browser.close();server.close();}})().catch(e=>{console.error(e);server.close();process.exitCode=1;});
