/* Embedded in index.html by embed-studio.cjs; uses the existing app store and sync. */
var StudioUI=(function(){
  var infoOnly=false;
  userTemplates=TemplateText.library(userTemplates);
  var S=window.MinMaxStudio, KEY='trainingsplan.v1.builderDraft', state=null, picker=null, info=null, previous=null;
  var dlg=document.getElementById('studio-dialog'),body=document.getElementById('studio-body'),footer=document.getElementById('studio-footer');
  var paths={back:'M19 12H5m6-6-6 6 6 6',close:'m6 6 12 12M18 6 6 18',down:'m6 9 6 6 6-6',up:'m6 15 6-6 6 6',info:'M12 11v6m0-10v.1',plus:'M12 5v14M5 12h14',arrow:'M5 12h14m-6-6 6 6-6 6',search:'m16 16 4 4M18 10a8 8 0 1 1-16 0 8 8 0 0 1 16 0'};
  function icon(name){var s=svg('svg',{viewBox:'0 0 24 24',fill:'none',stroke:'currentColor','stroke-width':'1.8','stroke-linecap':'round','stroke-linejoin':'round','aria-hidden':'true'});if(name==='info')svg('circle',{cx:12,cy:12,r:9},s);svg('path',{d:paths[name]||paths.arrow},s);return s;}
  function button(label,fn,cls){var b=h('button',{type:'button',class:cls||'studio-secondary',text:label});b.addEventListener('click',fn);return b;}
  function iconButton(name,label,fn){var b=button('',fn,'studio-icon');b.setAttribute('aria-label',label);b.appendChild(icon(name));return b;}
  function fresh(){return {screen:'home',step:0,input:S.config(),draft:null,templateId:null,templateQuery:'',templateFilter:'',origin:'',selectedDay:0};}
  function persist(){if(!state)return;try{store.write(KEY,state);}catch(e){toast(e.message);}}
  function change(screen){state.screen=screen;persist();render();}
  function title(text){document.getElementById('studio-title').textContent=text;}
  function heading(text,lead){body.appendChild(h('h3',{text:text}));if(lead)body.appendChild(h('p',{class:'studio-lead',text:lead}));}
  function note(text,cls){body.appendChild(h('p',{class:cls||'studio-note',text:text}));}
  function action(text,fn,disabled){var b=button(text,fn,'studio-primary');b.disabled=!!disabled;footer.appendChild(b);return b;}
  function field(label,value,fn,opts,parent){var wrap=h('label',{class:'studio-label',text:label}),inp=h('input',Object.assign({class:'studio-input',type:'text',maxlength:'80'},opts||{}));inp.value=value==null?'':String(value);wrap.appendChild(inp);(parent||body).appendChild(wrap);inp.addEventListener('input',function(){fn(inp.value,inp);persist();});return inp;}
  function choice(label,detail,selected,fn){var b=button('',fn,'studio-choice'+(selected?' is-selected':''));b.setAttribute('aria-pressed',selected?'true':'false');b.appendChild(h('strong',{text:label}));if(detail)b.appendChild(h('span',{text:detail}));return b;}
  function thumbnail(e,cls){var img=h('img',{class:cls||'studio-thumb',src:'assets/studio/'+e.image+'.webp',alt:'Geräteillustration: '+S.equipment[e.equipment],loading:'lazy',width:'68',height:'68'});img.addEventListener('error',function(){img.hidden=true;},{once:true});return img;}
  function open(home){if(!S)return;picker=null;info=null;infoOnly=false;var saved=store.read(KEY,null);state=saved&&saved.version!==-1&&saved.input&&['home','interview','templates','mode','manual','editor'].includes(saved.screen)?saved:fresh();state.input=S.config(state.input);if(state.draft&&(!Array.isArray(state.draft.days)||!state.draft.days.length||state.draft.days.some(function(d){return !d||typeof d.name!=='string'||!Array.isArray(d.exercises);})))state=fresh();if(home)state.screen='home';render();show();}
  function show(){if(!dlg.open){if(typeof dlg.showModal==='function')dlg.showModal();else dlg.setAttribute('open','');}}
  function close(){persist();if(typeof dlg.close==='function')dlg.close();else dlg.removeAttribute('open');}
  function back(){if(info){if(infoOnly){close();info=null;infoOnly=false;state=previous;previous=null;return;}info=null;render();return;}if(picker){if(picker.external){close();picker=null;return;}picker=null;render();return;}if(state.screen==='interview'){if(state.step>0){state.step--;persist();render();}else change('home');}else if(state.screen==='editor')change(state.origin==='interview'?'interview':state.origin==='template'?'mode':state.origin==='import'?'templates':state.origin==='plan'?'home':'manual');else if(state.screen==='mode')change('templates');else change('home');}
  function render(){body.replaceChildren();footer.replaceChildren();body.scrollTop=0;document.getElementById('studio-back').disabled=false;
    if(!S){title('Neuer Plan');heading('Bibliothek nicht verfügbar');note('Die manuelle Planerstellung bleibt verfügbar.');action('Manuellen Plan anlegen',function(){close();openLegacyNewPlan();});return;}
    if(info){renderInfo();return;}if(picker){renderPicker();return;}
    if(!state)state=fresh();
    if(state.screen==='home')home();else if(state.screen==='interview')interview();else if(state.screen==='templates')templateList();else if(state.screen==='mode')mode();else if(state.screen==='manual')manual();else if(state.screen==='editor')editor();
  }
  function home(){title('MinMax Studio');document.getElementById('studio-back').disabled=true;var hero=h('div',{class:'studio-home-hero'});hero.appendChild(h('p',{class:'studio-eyebrow',text:'DEIN PLAN. DEIN TRAINING.'}));hero.appendChild(h('h3',{text:'Training, das zu dir passt.'}));hero.appendChild(h('p',{text:'Geführt starten, eine Vorlage anpassen oder frei zusammenstellen.'}));hero.appendChild(h('p',{class:'studio-meta',text:'1–5 Tage · 30–120 Minuten · Offline verfügbar'}));body.appendChild(hero);
    if(state.draft||state.origin){body.appendChild(button('Gespeicherten Entwurf fortsetzen',function(){change(state.draft?'editor':state.origin==='interview'?'interview':state.origin==='template'?'templates':'manual');},'studio-primary'));note('Dein Entwurf bleibt auf diesem Gerät gespeichert.');}
    var grid=h('div',{class:'studio-grid studio-home-grid'});
    grid.appendChild(choice('Plan empfehlen','Sechs kurze Fragen. Ein passender Startplan.',false,function(){state.origin='interview';state.step=0;change('interview');}));
    grid.appendChild(choice('Vorlage wählen','Bewährte Strukturen mit verständlichen Vor- und Nachteilen.',false,function(){state.origin='template';change('templates');}));
    grid.appendChild(choice('Selbst zusammenstellen','Trainingstage und Übungen ganz nach deinen Vorstellungen.',false,function(){state.origin='manual';change('manual');}));body.appendChild(grid);
    if(planById(activePlanId)){var tools=h('div',{class:'studio-template-tools'});tools.appendChild(button('Aktuellen Plan als Vorlage öffnen',fromCurrentPlan));body.appendChild(tools);note('Übungen, Reihenfolge, Sätze und Wiederholungen übernehmen. Ohne Trainingsdaten.');}
    if(state.draft||state.origin)footer.appendChild(button('Entwurf verwerfen',discard));else footer.appendChild(h('span',{class:'studio-meta',text:'Bestehende Pläne und Trainings bleiben erhalten.'}));
  }
  function discard(){askConfirm({title:'Entwurf verwerfen?',lead:'Nur dieser Baukasten-Entwurf wird entfernt. Deine gespeicherten Pläne bleiben erhalten.',okLabel:'Verwerfen',danger:true}).then(function(yes){if(yes){state=fresh();persist();render();}});}
  var goalNames={muscle:'Muskelaufbau',strength:'Kraftzuwachs',max:'Maximalkraft'},levelNames={beginner:'Anfänger',intermediate:'Fortgeschritten',expert:'Experte'};
  function interview(){title('Plan empfehlen');var c=state.input,step=state.step||0,bar=h('div',{class:'studio-stepper','aria-label':'Schritt '+(step+1)+' von 6'});for(var i=0;i<6;i++)bar.appendChild(h('span',{class:i<=step?'is-done':''}));body.appendChild(h('p',{class:'studio-step-label',text:(step+1)+' von 6'}));body.appendChild(bar);var grid=h('div',{class:'studio-grid'});
    if(step===0){heading('Was möchtest du erreichen?','Dein Ziel bestimmt die Startvorgaben für Sätze und Wiederholungen.');Object.keys(goalNames).forEach(function(v){grid.appendChild(choice(goalNames[v],v==='muscle'?'Muskelmasse aufbauen.':v==='strength'?'In grundlegenden Bewegungen stärker werden.':'Schwerere Lasten kontrolliert bewegen.',c.goal===v,function(){c.goal=v;persist();render();}));});body.appendChild(grid);}
    if(step===1){heading('Deine Erfahrung','Damit dein Plan zu deinem Können passt.');Object.keys(levelNames).forEach(function(v){grid.appendChild(choice(levelNames[v],v==='beginner'?'Du hast wenig oder keine Erfahrung im Krafttraining.':v==='intermediate'?'Du trainierst regelmäßig und kennst die Grundübungen.':'Du hast langjährige Erfahrung und trainierst strukturiert.',c.level===v,function(){c.level=v;persist();render();}));});body.appendChild(grid);var row=h('div',{class:'studio-number-row'});body.appendChild(h('p',{class:'studio-label',text:'Jahre durchgängigen Trainings'}));body.appendChild(row);row.appendChild(button('Ich starte gerade',function(){c.years=0;persist();render();}));field('Jahre',c.years,function(v){c.years=Math.max(0,Number(v.replace(',','.'))||0);},{inputmode:'decimal',maxlength:'5'},row);note('„Ich starte gerade“ setzt deine Erfahrung auf 0 Jahre.');}
    if(step===2){heading('Wie oft hast du Zeit?','Wähle ein Pensum, das du regelmäßig einhalten kannst.');var chips=h('div',{class:'studio-chips'});for(var day=1;day<=5;day++)(function(v){var b=button(v+(v===1?' Tag':' Tage'),function(){c.days=v;persist();render();},'studio-chip'+(c.days===v?' is-selected':''));b.setAttribute('aria-pressed',String(c.days===v));chips.appendChild(b);})(day);body.appendChild(chips);note('Ein bis fünf Trainingstage pro Woche.');}
    if(step===3){heading('Zeit für dein Training','Inklusive Aufwärmen, Pausen und Gerätewechseln.');var number=h('p',{class:'studio-value',text:c.minutes+' '});number.appendChild(h('span',{class:'studio-unit',text:'Minuten'}));body.appendChild(number);var range=h('input',{class:'studio-range',type:'range',min:'30',max:'120',step:'5','aria-label':'Minuten pro Training'});range.value=c.minutes;range.addEventListener('input',function(){c.minutes=Number(range.value);number.firstChild.textContent=c.minutes+' ';persist();});body.appendChild(range);note('30 Minuten bis 2 Stunden. Die Zeitangaben im Plan sind Schätzungen.');}
    if(step===4){heading('Wie trainierst du gern?','Wir gehen von einem ausgestatteten Fitnessstudio aus.');[['machine','Maschinen','Einfach einzustellen und gut für den Einstieg.'],['mixed','Gemischt','Maschinen, Kabelzug und freie Gewichte.'],['free','Freie Gewichte','Kurzhanteln und Langhanteln im Vordergrund.']].forEach(function(v){grid.appendChild(choice(v[1],v[2],c.preference===v[0],function(){c.preference=v[0];persist();render();}));});body.appendChild(grid);}
    if(step===5){heading('Deine Muskelprioritäten','Optional: bis zu drei Bereiche, in deiner gewünschten Reihenfolge.');var chips=h('div',{class:'studio-chips'});Object.keys(S.muscles).forEach(function(m){var n=c.priorities.indexOf(m),b=button((n>=0?(n+1)+'. ':'')+S.muscles[m],function(){if(n>=0)c.priorities.splice(n,1);else if(c.priorities.length<3)c.priorities.push(m);else{toast('Bis zu drei Prioritäten wählen.');return;}persist();render();},'studio-chip'+(n>=0?' is-selected':''));b.setAttribute('aria-pressed',String(n>=0));chips.appendChild(b);});body.appendChild(chips);note('Der restliche Körper bleibt im Plan berücksichtigt.');}
    footer.appendChild(button('Zurück',back));action(step===5?'Plan erstellen':'Weiter',function(){if(step<5){state.step++;persist();render();}else{state.draft=S.generate(c);state.selectedDay=0;change('editor');}});
  }
  function ownTemplates(){return userTemplates.filter(function(t){return !t.deleted;});}
  function allTemplates(){return ownTemplates().map(function(t){return Object.assign({},t,{personal:true,days:[t.days.length],structure:t.days});}).concat(S.templates);}
  function templateList(){title('Vorlagen');heading('Deine Trainingsstruktur',S.templates.length+' Standardvorlagen · '+ownTemplates().length+' eigene');
    var tools=h('div',{class:'studio-template-tools'});tools.appendChild(button('Textvorlage importieren',importTemplate));body.appendChild(tools);note('Eigene Vorlagen speichern nur die Planstruktur. Importierte Dateien öffnest du zuerst als Entwurf.');
    var help=h('details');help.appendChild(h('summary',{class:'studio-secondary',text:'So sieht eine Textvorlage aus'}));help.appendChild(h('pre',{class:'studio-template-help',text:'MinMax-Vorlage: 1\nPlan: Mein Plan\n\n[Oberkörper]\nBrustpresse | 3 | 8-12\nRudern | 3 | 10\nKlimmzüge | 2 | 6-8 | Körpergewicht'}));body.appendChild(help);
    field('Vorlage suchen',state.templateQuery||'',function(v){state.templateQuery=v;list();},{type:'search',placeholder:'Vorlage suchen'});var chips=h('div',{class:'studio-chips'});[['','Alle'],['low','1–3 Tage'],['high','4–5 Tage']].forEach(function(v){var b=button(v[1],function(){state.templateFilter=v[0];persist();render();},'studio-chip'+(state.templateFilter===v[0]?' is-selected':''));b.setAttribute('aria-pressed',String(state.templateFilter===v[0]));chips.appendChild(b);});body.appendChild(chips);var box=h('div');body.appendChild(box);var go=action('Vorlage bearbeiten',function(){change('mode');},!state.templateId);
    function list(){box.replaceChildren();var matches=allTemplates().filter(function(t){return TemplateText.normalize(t.name).includes(TemplateText.normalize(state.templateQuery))&&(!state.templateFilter||(state.templateFilter==='low'?Math.min.apply(null,t.days)<=3:t.days.some(function(n){return n>=4&&n<=5;})));});if(!matches.some(function(t){return t.id===state.templateId;})){state.templateId=null;go.disabled=true;persist();}if(!matches.length)box.appendChild(h('p',{class:'studio-note',text:'Keine passende Vorlage gefunden.'}));var group='';matches.forEach(function(t){var next=t.personal?'Eigene Vorlagen':'Standardvorlagen';if(group!==next){box.appendChild(h('h4',{class:'studio-note',text:next}));group=next;}var open=state.templateId===t.id,card=h('section',{class:'studio-template'+(open?' is-open':'')}),toggle=button('',function(){state.templateId=open?null:t.id;persist();list();},'studio-template-toggle');toggle.setAttribute('aria-expanded',String(open));toggle.setAttribute('aria-controls','studio-template-'+t.id);toggle.appendChild(h('strong',{text:t.name}));toggle.appendChild(h('span',{class:'studio-pill',text:t.days.length>1?'1–3 Tage':t.days[0]+(t.days[0]===1?' Tag':' Tage')}));var chevron=icon(open?'up':'down');chevron.classList.add('studio-chevron');toggle.appendChild(chevron);card.appendChild(toggle);if(open){var content=h('div',{class:'studio-template-content',id:'studio-template-'+t.id});if(t.personal){content.appendChild(h('p',{text:'Deine gespeicherte Planstruktur – ohne Gewichte oder Trainingsverlauf.'}));var days=h('ul');t.structure.forEach(function(d){days.appendChild(h('li',{text:d.name+' · '+d.exercises.filter(function(e){return !e.empty;}).length+' Übungen'}));});content.appendChild(days);var actions=h('div',{class:'studio-template-tools'});actions.appendChild(button('Vorlage als Text exportieren',function(){exportTemplate(t);}));actions.appendChild(button('Vorlage löschen',function(){removeTemplate(t.id);}));content.appendChild(actions);}else{content.appendChild(h('p',{text:t.description}));[['Vorteile',t.pros,''],['Zu beachten',t.cons,'caution']].forEach(function(group){content.appendChild(h('h4',{class:group[2],text:group[0]}));var ul=h('ul');group[1].forEach(function(text){ul.appendChild(h('li',{text:text}));});content.appendChild(ul);});}card.appendChild(content);}box.appendChild(card);});go.disabled=!state.templateId;}
    list();
  }
  function mode(){title('Vorlage bearbeiten');var t=allTemplates().find(function(t){return t.id===state.templateId;});if(!t){change('templates');return;}heading(t.name,t.personal?'Deine eigenen Übungen übernehmen oder die Plätze neu füllen.':t.id==='roman'?'Romans Originalplan übernehmen oder die vier Tage selbst füllen.':'Mit bewährten Übungen starten oder die Struktur selbst füllen.');if(t.id==='full'){state.input.days=Math.min(3,state.input.days);note('Wie viele Trainingstage möchtest du?');var chips=h('div',{class:'studio-chips'});[1,2,3].forEach(function(n){chips.appendChild(button(n+' '+(n===1?'Tag':'Tage'),function(){state.input.days=n;persist();render();},'studio-chip'+(state.input.days===n?' is-selected':'')));});body.appendChild(chips);}else state.input.days=t.days[0];var grid=h('div',{class:'studio-grid'});[[t.personal?'Mit meinen Übungen':'Mit Standardübungen',false,'Ein editierbarer Startplan mit einfachen Übungen.'],['Selbst füllen',true,'Muskelhinweise geben jedem leeren Platz eine Richtung.']].forEach(function(v){grid.appendChild(choice(v[0],t.personal&&!v[1]?'Gespeicherte Übungen, Sätze und Wiederholungen.':t.id==='roman'&&!v[1]?'25 Originalübungen mit Sätzen und Wiederholungen. Ohne Gewichte oder Verlauf.':v[2],false,function(){state.draft=t.personal?Object.assign(TemplateText.clean({name:t.name,days:t.structure}),{input:S.config(state.input)}):S.create(t.id,state.input,v[1]);if(t.personal&&v[1])state.draft.days.forEach(function(d){d.exercises=d.exercises.map(function(e){return {empty:true,targetMuscle:e.targetMuscle||null};});});state.selectedDay=0;state.origin='template';change('editor');}));});body.appendChild(grid);footer.appendChild(button('Zurück',back));}
  function manual(){title('Eigener Plan');heading('Dein Plan. Deine Auswahl.','Lege die Struktur fest. Übungen wählst du im nächsten Schritt.');field('Planname',state.manualName||'Mein Trainingsplan',function(v){state.manualName=v;});var chips=h('div',{class:'studio-chips'});body.appendChild(h('p',{class:'studio-label',text:'Trainingstage'}));[1,2,3,4,5].forEach(function(n){chips.appendChild(button(n+' '+(n===1?'Tag':'Tage'),function(){state.input.days=n;persist();render();},'studio-chip'+(state.input.days===n?' is-selected':'')));});body.appendChild(chips);field('Übungsplätze je Tag',state.slotCount||5,function(v){state.slotCount=Math.max(1,Math.min(20,parseInt(v,10)||1));},{type:'number',min:'1',max:'20',inputmode:'numeric'});action('Plan zusammenstellen',function(){state.draft={name:(state.manualName||'Mein Trainingsplan').trim(),input:S.config(state.input),days:Array.from({length:state.input.days},function(_,i){return {name:'Tag '+(i+1),exercises:Array.from({length:state.slotCount||5},function(){return {empty:true};})};})};state.selectedDay=0;state.origin='manual';change('editor');});}
  function editor(){title('Plan bearbeiten');var draft=state.draft;if(!draft){change('home');return;}heading('Dein Trainingsplan','Alles bleibt anpassbar. Gespeichert wird erst am Ende.');if(draft.notice)note(draft.notice,'studio-info-note');field('Planname',draft.name,function(v){draft.name=v;});var tools=h('div',{class:'studio-template-tools'});tools.appendChild(button('Als eigene Vorlage speichern',saveTemplate));tools.appendChild(button('Vorlage als Text exportieren',function(){exportTemplate(draft);}));body.appendChild(tools);note('Vorlagen enthalten nur Übungen, Sätze und Wiederholungen. Ein zusätzlicher Trainingsplan entsteht erst mit „Plan speichern“.');var tabs=h('div',{class:'studio-day-tabs'});state.selectedDay=Math.min(state.selectedDay||0,draft.days.length-1);draft.days.forEach(function(d,i){tabs.appendChild(button(d.name||'Tag '+(i+1),function(){state.selectedDay=i;persist();render();},'studio-chip'+(state.selectedDay===i?' is-selected':'')));});body.appendChild(tabs);var day=draft.days[state.selectedDay];field('Name des Trainingstags',day.name,function(v){day.name=v;});var duration=h('p',{class:'studio-note',id:'studio-duration'});body.appendChild(duration);function durationText(){duration.textContent=day.exercises.some(function(e){return !e.empty;})?'Geschätzte Dauer: '+S.estimate(day,draft.input)+' Min. · '+day.exercises.filter(function(e){return !e.empty;}).length+' Übungen':'Wähle Übungen für diesen Trainingstag.';}durationText();
    day.exercises.forEach(function(row,i){var card=h('section',{class:'studio-editor-row'+(row.empty?' studio-empty':'')}),line=h('div',{class:'studio-ex-title'}),e=S.byId[row.catalogueId];if(e)line.appendChild(thumbnail(e));line.appendChild(h('strong',{text:(i+1)+'. '+(row.empty?(S.muscles[row.targetMuscle]||'Übung auswählen'):row.name)}));if(e)line.appendChild(iconButton('info','Information zu '+row.name,function(){info=e;render();}));card.appendChild(line);
      if(!row.empty){var fields=h('div',{class:'studio-specs'});[['Sätze','sets'],['Wdh. von','rmin'],['Wdh. bis','rmax']].forEach(function(pair){field(pair[0],row[pair[1]],function(v){row[pair[1]]=Number(v);durationText();},{type:'number',min:'1',max:'99',inputmode:'numeric',maxlength:'2'},fields);});card.appendChild(fields);}
      var actions=h('div',{class:'studio-editor-actions'});actions.appendChild(button(row.empty?'Übung wählen':'Ersetzen',function(){picker={day:state.selectedDay,row:i,query:'',muscle:row.targetMuscle||'',equipment:'',limit:30};render();}));if(i>0)actions.appendChild(button('↑ Nach oben',function(){var x=day.exercises.splice(i,1)[0];day.exercises.splice(i-1,0,x);persist();render();}));if(i<day.exercises.length-1)actions.appendChild(button('↓ Nach unten',function(){var x=day.exercises.splice(i,1)[0];day.exercises.splice(i+1,0,x);persist();render();}));actions.appendChild(button('Entfernen',function(){day.exercises.splice(i,1);persist();render();}));card.appendChild(actions);body.appendChild(card);
    });body.appendChild(button('＋ Übung hinzufügen',function(){day.exercises.push({empty:true});persist();render();}));footer.appendChild(button('Zurück',back));action('Plan speichern',commit);
  }
  function renderPicker(){title('Übungen auswählen');heading('Finde deine Übung',S.catalogue.length+' Übungen · nach Muskel und Gerät filtern');var p=picker;
    field('Übung suchen',p.query,function(v){p.query=v;p.limit=30;results();},{type:'search',placeholder:'Name oder englischer Begriff'});
    var filters=h('div',{class:'studio-list-controls'});body.appendChild(filters);function select(label,options,value,fn){var wrap=h('label',{class:'studio-label',text:label}),sel=h('select',{class:'studio-select','aria-label':label});options.forEach(function(v){sel.appendChild(h('option',{value:v[0],text:v[1]}));});sel.value=value;sel.addEventListener('change',function(){fn(sel.value);p.limit=30;results();});wrap.appendChild(sel);filters.appendChild(wrap);}
    select('Muskel',[['','Alle Muskeln'],['arms','Arme'],['legs','Beine']].concat(Object.keys(S.muscles).map(function(m){return [m,S.muscles[m]];})),p.muscle,function(v){p.muscle=v;});select('Gerät',[['','Alle Geräte']].concat(Object.keys(S.equipment).map(function(e){return [e,S.equipment[e]];})),p.equipment,function(v){p.equipment=v;});
    var count=h('p',{class:'studio-meta','aria-live':'polite'}),list=h('div',{class:'studio-results'});body.appendChild(count);body.appendChild(list);footer.appendChild(button('Eigene Übung eingeben',manualExercise));
    function results(){list.replaceChildren();var matches=S.search(p.query,p.muscle,p.equipment);count.textContent=matches.length+' passende Übungen';matches.slice(0,p.limit).forEach(function(e){var card=h('article',{class:'studio-result'});card.appendChild(thumbnail(e));var main=h('div',{class:'studio-result-main'});main.appendChild(h('strong',{text:e.name}));main.appendChild(h('p',{class:'studio-meta',text:e.muscles.map(function(m){return S.muscles[m];}).join(' · ')}));main.appendChild(h('span',{class:'studio-pill',text:S.equipment[e.equipment]}));if(p.muscle&&!e.muscles.includes(p.muscle)&&e.secondary.includes(p.muscle))main.appendChild(h('p',{class:'studio-meta',text:'Sekundär beteiligt'}));card.appendChild(main);var actions=h('div',{class:'studio-result-actions'});actions.appendChild(iconButton('info','Information zu '+e.name,function(){info=e;render();}));actions.appendChild(iconButton('plus',e.name+' auswählen',function(){selectExercise(e);}));card.appendChild(actions);list.appendChild(card);});if(matches.length>p.limit)list.appendChild(button('Weitere Übungen anzeigen',function(){p.limit+=30;results();}));if(!matches.length)list.appendChild(h('p',{class:'studio-note',text:'Keine Treffer. Ändere Suche oder Filter, oder gib eine eigene Übung ein.'}));}
    results();
  }
  function renderInfo(){title('Übungswissen');var e=info;heading(e.name,e.muscles.map(function(m){return S.muscles[m];}).join(' · '));body.appendChild(thumbnail(e,'studio-info-image'));[['Wofür geeignet?',e.description],['Was bringt dir das?',e.benefit],['Gerät & Ausgangsposition',e.setup]].forEach(function(pair){var card=h('section',{class:'studio-info-card'});card.appendChild(h('h4',{text:pair[0]}));card.appendChild(h('p',{text:pair[1]}));body.appendChild(card);});var cues=h('section',{class:'studio-info-card cues'});cues.appendChild(h('h4',{text:'Cues · Darauf achten'}));var ul=h('ul');e.cues.forEach(function(c){ul.appendChild(h('li',{text:c}));});cues.appendChild(ul);body.appendChild(cues);var links=h('div',{class:'studio-info-links'});links.appendChild(h('a',{class:'studio-secondary',href:e.tutorial||'https://www.youtube.com/results?search_query='+encodeURIComponent(e.name+' Übung Anleitung'),target:'_blank',rel:'noopener noreferrer',text:e.tutorial?'Tutorial & Anleitung ↗':'Tutorials suchen ↗'}));body.appendChild(links);note('Externe Tutorials benötigen Internet. Gerätebilder zeigen den Gerätetyp.');var attr=h('p',{class:'studio-attribution',text:'Katalog: wger · '+e.authors.join(', ')+' · Bearbeitet für MinMax. '});attr.appendChild(h('a',{href:e.source,target:'_blank',rel:'noopener noreferrer',text:'Quelle'}));attr.appendChild(document.createTextNode(' · '));attr.appendChild(h('a',{href:e.licenseUrl,target:'_blank',rel:'noopener noreferrer',text:e.license}));if(e.classificationLicense){attr.appendChild(document.createTextNode(' · Geräte-/Muskelangaben: '));attr.appendChild(h('a',{href:e.classificationLicense.url,target:'_blank',rel:'noopener noreferrer',text:e.classificationLicense.name}));}body.appendChild(attr);action('Zurück',back);}
  function duplicate(e){if(picker.external){var ex=POOL[picker.exId],day=ex&&dayById(ex.dayId);return day&&day.ex.some(function(row){return row.id!==picker.exId&&!row.empty&&((e.id&&row.catalogueId===e.id)||S.normalize(row.n)===S.normalize(e.name));});}return state.draft.days[picker.day].exercises.some(function(row,i){return i!==picker.row&&!row.empty&&((e.id&&row.catalogueId===e.id)||S.normalize(row.name)===S.normalize(e.name));});}
  function selectExercise(e){if(duplicate(e)){toast('Diese Übung steht bereits in diesem Trainingstag.');return;}if(picker.external){applyExternal(e);return;}var day=state.draft.days[picker.day],old=day.exercises[picker.row],row=S.prescription(e,S.config(state.draft.input));if(!old.empty){row.sets=old.sets;row.rmin=old.rmin;row.rmax=old.rmax;}day.exercises[picker.row]=row;picker=null;persist();render();}
  function manualExercise(){var p=picker;info=null;title('Eigene Übung');body.replaceChildren();footer.replaceChildren();heading('Deine eigene Übung','Name, Sätze und Wiederholungen frei festlegen.');var name='',sets=2,min=8,max=12;field('Übungsname','',function(v){name=v;});field('Sätze',sets,function(v){sets=Number(v);},{type:'number',min:'1',max:'99'});field('Wiederholungen von',min,function(v){min=Number(v);},{type:'number',min:'1',max:'99'});field('Wiederholungen bis',max,function(v){max=Number(v);},{type:'number',min:'1',max:'99'});footer.appendChild(button('Zurück',function(){picker=p;render();}));action('Übung übernehmen',function(){if(!name.trim()||[sets,min,max].some(function(v){return !Number.isInteger(v)||v<1||v>99;})){toast('Name und Zahlen zwischen 1 und 99 eingeben.');return;}picker=p;var e={id:null,name:name.trim(),muscles:[],equipment:'bodyweight',main:false};if(duplicate(e)){toast('Diese Übung steht bereits im Tag.');return;}if(p.external){applyExternal(e,{sets:sets,rmin:Math.min(min,max),rmax:Math.max(min,max)});return;}state.draft.days[p.day].exercises[p.row]={name:name.trim(),sets:sets,rmin:Math.min(min,max),rmax:Math.max(min,max),rest:90};picker=null;persist();render();});}
  function applyExternal(e,spec){var p=picker,old=POOL[p.exId],day=old&&dayById(old.dayId);if(!old||!day){close();picker=null;return;}var chosen;
    if(old.empty){chosen=customEx[old.id];delete chosen.empty;chosen.n=e.name;Object.assign(chosen,spec||{sets:2,rmin:8,rmax:12});chosen.p='';}
    else{var err=swapExercise(day.id,old.id,e.name);if(err){toast(err);return;}chosen=dayById(day.id).ex.find(function(x){return S.normalize(x.n)===S.normalize(e.name);});if(spec)Object.assign(chosen,spec);customEx[chosen.id]=chosen;}
    if(e.id)chosen.catalogueId=e.id;else delete chosen.catalogueId;savePlan();rebuildPlanRegistry();Sync.pushPlan();picker=null;close();state=previous;previous=null;rebuildAll();toast(e.name+' übernommen');
  }
  function openPicker(exId){if(!S)return;infoOnly=false;var ex=POOL[exId];if(!ex)return;previous=state;state=null;picker={external:true,exId:exId,query:'',muscle:ex.targetMuscle||'',equipment:'',limit:30};info=null;render();show();}

  function flow(){return {owner:store.owner,ui:ui,state:state};}
  function currentFlow(c){return c.owner===store.owner&&c.ui===ui&&c.state===state&&dlg.open;}
  function saveLibrary(items){if(!store.available)throw new Error('Der Kontospeicher ist nicht verfügbar. Bitte zuerst die Datensicherung prüfen.');var next=TemplateText.library(items);if(next.filter(function(t){return !t.deleted;}).length>50||new Blob([JSON.stringify(next)]).size>400000)throw new Error('Deine Vorlagenbibliothek ist voll. Exportiere und entferne zuerst eine Vorlage.');store.write(K_TEMPLATES,next);userTemplates=next;Sync.pushPlan();}
  async function saveTemplate(){var c=flow();try{var draft=TemplateText.clean(state.draft),old=ownTemplates().find(function(t){return TemplateText.normalize(t.name)===TemplateText.normalize(draft.name);});if(old){var yes=await askConfirm({title:'Vorlage ersetzen?',lead:'„'+old.name+'“ wird durch diesen Entwurf ersetzt. Deine Trainingspläne und Trainings bleiben unverändert.',okLabel:'Vorlage ersetzen'});if(!yes||!currentFlow(c))return;}var id=old?old.id:'tpl-'+Date.now().toString(36)+'-'+Math.random().toString(36).slice(2,9);saveLibrary(userTemplates.filter(function(t){return t.id!==id;}).concat([Object.assign({id:id},draft)]));toast('Eigene Vorlage gespeichert');}catch(e){if(currentFlow(c))toast(e.message);}}
  async function removeTemplate(id){var c=flow(),t=ownTemplates().find(function(t){return t.id===id;});if(!t)return;var yes=await askConfirm({title:'Vorlage löschen?',lead:'Nur die Vorlage „'+t.name+'“ wird entfernt. Daraus erstellte Pläne und Trainings bleiben erhalten.',okLabel:'Vorlage löschen',danger:true});if(!yes||!currentFlow(c))return;try{saveLibrary(userTemplates.filter(function(t){return t.id!==id;}).concat([{id:id,deleted:true}]));state.templateId=null;persist();render();toast('Vorlage gelöscht');}catch(e){toast(e.message);}}
  function exportTemplate(draft){try{if(draft.personal)draft={name:draft.name,days:draft.structure};var text=TemplateText.stringify(draft),blob=new Blob([text],{type:'text/plain;charset=utf-8'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=draft.name.replace(/[^a-zA-Z0-9äöüÄÖÜß_-]+/g,'-').slice(0,70)+'-minmax-vorlage.txt';document.body.appendChild(a);a.click();a.remove();setTimeout(function(){URL.revokeObjectURL(url);},1000);}catch(e){toast(e.message);}}
  async function takeDraft(draft,origin,c){if(!currentFlow(c))return;if(state.draft){var yes=await askConfirm({title:'Entwurf ersetzen?',lead:'Der neue Vorlagenentwurf ersetzt deinen bisherigen Baukasten-Entwurf. Gespeicherte Pläne und Trainings bleiben erhalten.',okLabel:'Entwurf ersetzen'});if(!yes||!currentFlow(c))return;}state.draft=Object.assign(TemplateText.clean(draft),{input:S.config(state.input)});state.selectedDay=0;state.origin=origin;change('editor');}
  function fromCurrentPlan(){var c=flow(),p=planById(activePlanId);if(!p)return;try{var d={name:p.name,days:DAYS.map(function(day){return {name:day.name,exercises:day.ex.map(function(e){return e.empty?{empty:true,targetMuscle:e.targetMuscle}:{name:e.n,sets:e.sets,rmin:e.rmin,rmax:e.rmax,bodyweight:!!e.bodyweight,catalogueId:e.catalogueId,targetMuscle:e.targetMuscle};})};})};takeDraft(d,'plan',c).catch(function(e){if(currentFlow(c))toast(e.message);});}catch(e){toast(e.message);}}
  function importTemplate(){var c=flow(),input=h('input',{type:'file',accept:'.txt,text/plain','aria-label':'Textvorlage auswählen'});input.hidden=true;body.appendChild(input);input.addEventListener('change',function(){var file=input.files&&input.files[0];input.remove();if(!file)return;if(file.size>131072){toast('Die Textvorlage ist zu groß (maximal 128 KB).');return;}var reader=new FileReader();reader.onerror=function(){if(currentFlow(c))toast('Die Datei konnte nicht gelesen werden.');};reader.onload=function(){if(!currentFlow(c))return;try{var draft=TemplateText.parse(String(reader.result),S);takeDraft(draft,'import',c).catch(function(e){if(currentFlow(c))toast(e.message);});}catch(e){toast(e.message);}};reader.readAsText(file,'UTF-8');},{once:true});input.click();}

  function commit(){var d=state.draft;if(!d||!d.name.trim()||d.days.some(function(day){return !day.name.trim();})){toast('Plan und Trainingstage brauchen einen Namen.');return;}if(d.days.some(function(day){return day.exercises.some(function(e){return !e.empty&&(!e.name.trim()||[e.sets,e.rmin,e.rmax].some(function(v){return !Number.isInteger(v)||v<1||v>99;}));});})){toast('Sätze und Wiederholungen müssen zwischen 1 und 99 liegen.');return;}
    var planId='plan-'+Math.random().toString(36).slice(2,10);while(planById(planId))planId='plan-'+Math.random().toString(36).slice(2,10);var additions={},days=d.days.map(function(day,i){var dayId=planId+'-tag-'+(i+1),ids=[];day.exercises.forEach(function(e,j){var id=dayId+'-s'+(j+1);ids.push(id);additions[id]=e.empty?{id:id,empty:true,dayId:dayId,planId:planId,targetMuscle:e.targetMuscle||null}:{id:id,n:e.name.trim(),sets:e.sets,rmin:Math.min(e.rmin,e.rmax),rmax:e.rmax===e.rmin?null:Math.max(e.rmin,e.rmax),p:'',planTrend:null,dayId:dayId,planId:planId,catalogueId:e.catalogueId||null,bodyweight:!!e.bodyweight||!!(S.byId[e.catalogueId]&&S.byId[e.catalogueId].equipment==='bodyweight')};});return {id:dayId,name:day.name.trim(),base:ids};});
    var oldPlans=userPlans,oldExercises=customEx;userPlans=userPlans.concat([{id:planId,name:d.name.trim(),days:days,builder:{input:S.config(d.input),templateId:d.templateId||null}}]);customEx=Object.assign({},customEx,additions);
    try{savePlan();}catch(e){userPlans=oldPlans;customEx=oldExercises;try{savePlan();}catch(ignore){}toast(e.message);return;}
    state=fresh();persist();close();rebuildPlanRegistry();switchPlan(planId);Sync.pushPlan();toast('Trainingsplan gespeichert');
  }
  document.getElementById('studio-back').appendChild(icon('back'));document.getElementById('studio-back').addEventListener('click',back);document.getElementById('studio-close').appendChild(icon('close'));document.getElementById('studio-close').addEventListener('click',close);dlg.addEventListener('cancel',function(){persist();});
  return {open:open,close:close,openPicker:openPicker,openInfo:function(id){var e=S&&S.byId[id];if(!e)return;previous=state;state=null;picker=null;info=e;infoOnly=true;render();show();},render:render,commit:commit,get state(){return state;},get picker(){return picker;}};
})();
